# -*- coding: utf-8 -*-
"""Will I get placed? .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVLzuyBbHfGyA0ZGe9385q4lvoXb7RI2
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

df=pd.read_csv('/content/Placement_BeginnerTask01.csv');

df.head()

df.isnull().sum()

df.info()

"""placement count"""

sns.countplot(x="PlacementStatus",data=df)
plt.title("Placement Distrubution")
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True),annot=True,cmap="coolwarm")
plt.title("Feature Correlation")
plt.show()

"""cg vs placement"""

sns.boxplot(x="PlacementStatus",y="CGPA",data=df)
plt.title("CGPA vs Placement")
plt.show()

x = df.drop(["PlacementStatus", "StudentID"], axis=1)
categorical_cols = x.select_dtypes(include=['object']).columns
x = pd.get_dummies(x, columns=categorical_cols, drop_first=True)
y = df["PlacementStatus"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=LogisticRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

acc=accuracy_score(y_test,y_pred)
print(acc)

print(classification_report(y_test,y_pred))

cm=confusion_matrix(y_test,y_pred)
print(cm)

sns.heatmap(cm,annot=True,fmt="d")
plt.title("Confusion Matrix")
plt.show()

